stages:
  - build
  - test

build:
  stage: build
  services:
  - docker:dind

  script:
    - apk add --no-cache git
    - apk add --no-cache docker-cli-buildx
    - git clone https://gitlab.pflb.ru/pub/webtours.git
    - cd webtours
    - docker build -t webtours:v2 .
    - docker run --rm --name webtours -p 8085:80 -d webtours:v2

unit tests:
  stage: test
  script:
    - curl http://docker:8085
