stages:
  - build
  - test

image: docker:latest

variables:
  DOCKER_DRIVER: overlay2
  
services:
- docker:dind


build:
  stage: build
  script:
    - apk add --no-cache git docker-cli
    - git clone https://github.com/ihusainov/webtours.git
    - cd webtours
    - docker build -t webtours:v2 .
    - docker run --privileged --rm --name webtours -p 8085:80 -d webtours:v2


unit tests:
  stage: test
  script:
    - apk add --no-cache curl
    - curl http://localhost:8085

